flows:
  gtr:
    min_ai_prop: 0.1
    min_num_proj: 10
    gtr_orgs_filename: "ds/utils/gtr_org_names.txt"
  crunchbase:
    min_ai_prop: 0.1
    min_num_org_funded: 10
  glassai:
    bucket_name: "nesta-glass-ai"
    glassai_filename: "dap_uk_ai_map/inputs/glass_ai/nesta_ai.orgs.20220318.csv"
  utils:
    geoportal_url: "https://geoportal.statistics.gov.uk/datasets/national-statistics-postcode-lookup-february-2021"
